language: php

sudo: false

git:
    depth: 10

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
  include:
    - php: 7.0
      env: SYMFONY_VERSION=v3
    - php: 7.1
      env: SYMFONY_VERSION=v3
    - php: 7.2
      env: SYMFONY_VERSION=v3
    - php: 7.1
      env: SYMFONY_VERSION=v4
    - php: 7.2
      env: SYMFONY_VERSION=v4

before_install:
    - composer self-update
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; else INI_FILE=/etc/hhvm/php.ini; fi;

install:
    - composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update
    - composer require "php-http/guzzle6-adapter:^1.0" --no-update
    - composer install --prefer-source

script:
    - bin/phpunit

notifications:
  email:
    - payumsupport@forma-pro.com
