language: php

php:
  - 5.3
  - 5.4

env:
  - MONGO_VERSION=1.3.4

services: mongodb

before_script:
  - pecl -q install -f mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --dev --no-interaction --prefer-source

notifications:
  email:
    - payumsupport@forma-pro.com
